include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "lib/ffi/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    sdk_version_since: ignore
    implicit_dynamic_parameter: warning
    invalid_annotation_target: ignore
    implicit_dynamic_variable: ignore