name: aqua
description: AQUA - Bitcoin & Layer 2 Wallet

publish_to: "none"

version: 0.1.22+62

environment:
  sdk: ">=3.0.6 <=3.0.6"

dependencies:
  async: ^2.11.0
  bolt11_decoder: ^1.0.2
  collection: ^1.17.1
  confetti: ^0.7.0
  convert: ^3.1.1
  country_flags: ^2.2.0
  cupertino_icons: ^1.0.2
  decimal: ^2.3.3
  device_info_plus: ^9.0.2
  device_preview: ^1.1.0
  dio: ^5.3.2
  ffi: ^2.0.2
  file_picker: ^5.5.0
  flare_flutter: ^3.0.2
  flutter:
    sdk: flutter
  flutter_client_sse: ^2.0.0
  flutter_hooks: ^0.18.0
  flutter_inappwebview: ^5.7.2+3
  flutter_keyboard_visibility: ^5.4.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  flutter_screenutil: ^5.8.4
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  google_fonts: ^5.1.0
  hooks_riverpod: ^2.3.6
  http: ^0.13.6
  image_picker: ^1.0.1
  intl: any
  isolator: ^1.0.1
  json_annotation: ^4.8.1
  logger: ^1.4.0
  lottie: ^2.5.0
  mobile_scanner: ^3.3.0
  mocktail: ^1.0.2
  nanoid: ^1.0.0
  package_info_plus: ^4.1.0
  path_provider: ^2.1.1
  pointycastle: ^3.7.3
  pull_to_refresh_flutter3: ^2.0.2
  qr_flutter: 4.0.0
  restart_app: ^1.2.1
  riverpod_annotation: ^2.1.1
  rxdart: ^0.27.7
  share_plus: ^7.0.2
  shared_preferences: ^2.2.0
  skeletonizer: ^0.4.0
  uni_links: ^0.5.1
  url_launcher: ^6.1.12
  web_socket_channel: ^2.1.0
  webview_flutter: ^4.2.2
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  build_runner: ^2.4.6
  ffigen: ^8.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  riverpod_generator: ^2.2.4
  riverpod_lint: ^1.4.0
  test: ^1.24.1

dependency_overrides:
  http: ^0.13.5

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/
    - assets/asset_icons/
    - assets/animations/
    - assets/icon/
    - assets/marketplace/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"

fonts:
  - family: HelveticaNeue
    fonts:
      - asset: assets/fonts/HelveticaNeueHeavy.ttf
        weight: 800
      - asset: assets/fonts/HelveticaNeueBold.ttf
        weight: 700
      - asset: assets/fonts/HelveticaNeueMedium.ttf
        weight: 500
      - asset: assets/fonts/HelveticaNeueRegular.ttf
        weight: 400
      - asset: assets/fonts/HelveticaNeueLight.ttf
        weight: 300
      - asset: assets/fonts/HelveticaNeueThin.ttf
        weight: 200

ffigen:
  output: "lib/ffi/generated_bindings.dart"
  headers:
    entry-points:
      - "crypto/gdk-android-jni/include/gdk/gdk.h"
      - "rust-elements-wrapper/bindings.h"
  typedefs:
    include:
      - ".*"
  functions:
    expose-typedefs:
      include:
        - ".*"
  symbol-address:
    include:
      - ".*"
  structs:
    exclude:
      - "(.*)sigaction(.*)"
  unions:
    exclude:
      - "(.*)sigaction(.*)"
  llvm-path:
    - "/opt/local/libexec/llvm-10"
    - "/Library/Developer/CommandLineTools/usr"
